# -*- coding: utf-8 -*-
"""32513_Assignment2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jMvxtV5d_-6z7tTewFZAmdf9i3SOU3sn

# Bank Term-Deposit Subscription Prediction

**Project type:** Option 2 — practical machine learning system

The deployment setting used in this notebook is **pre-call / pre-outcome prediction**: the model uses information already available to the bank and returns a subscription propensity score. `duration` is excluded from the main model because it is not known before the call outcome is available.

The main evaluation keeps the original observation order and uses a 70/10/20 chronological split. SMOTE is applied **only to the transformed training set**.
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install -q imbalanced-learn
# %pip install -q pandas numpy matplotlib scikit-learn imbalanced-learn joblib
import os
from pathlib import Path
import copy
import json
import random

import joblib
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset

from imblearn.over_sampling import SMOTE
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.metrics import (
    accuracy_score,
    average_precision_score,
    confusion_matrix,
    ConfusionMatrixDisplay,
    f1_score,
    precision_recall_curve,
    precision_score,
    recall_score,
    roc_auc_score,
    roc_curve,
)

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 140)

FIG_DIR = Path("figures")
OUT_DIR = Path("outputs")
FIG_DIR.mkdir(exist_ok=True)
OUT_DIR.mkdir(exist_ok=True)

"""## Load the data"""

DATA_URL = ("https://raw.githubusercontent.com/jjdeng2009-rgb/32513-Assignment-2/refs/heads/main/Banking_Call_Data.csv")

df = pd.read_csv(DATA_URL)

print("Dataset shape:", df.shape)
df.head()

required_columns = {
    "age", "job", "marital", "education", "default", "balance", "housing", "loan",
    "contact", "day", "month", "duration", "campaign", "pdays", "previous", "poutcome", "y"
}

missing_columns = required_columns.difference(df.columns)
if missing_columns:
    raise ValueError(f"Missing columns: {sorted(missing_columns)}")

print("Duplicate rows:", df.duplicated().sum())
print("Explicit missing values:", int(df.isna().sum().sum()))
print(df["y"].value_counts())
print((df["y"].value_counts(normalize=True) * 100).round(2))

categorical_columns = [
    "job", "marital", "education", "default", "housing", "loan",
    "contact", "month", "poutcome"
]

unknown_counts = (df[categorical_columns] == "unknown").sum().sort_values(ascending=False)
unknown_counts[unknown_counts > 0]

# duration is useful for prediction, but it is not a valid pre-call input.
df.groupby("y")["duration"].agg(["count", "mean", "median"]).round(1)

"""## Task features and chronological split"""

numeric_columns = ["age", "balance", "day", "campaign", "pdays", "previous"]
model_features = numeric_columns + categorical_columns

y = (df["y"] == "yes").astype(int)

n = len(df)
train_end = int(n * 0.70)
val_end = int(n * 0.80)

train = df.iloc[:train_end].copy()
val = df.iloc[train_end:val_end].copy()
test = df.iloc[val_end:].copy()

y_train = (train["y"] == "yes").astype(int).to_numpy()
y_val = (val["y"] == "yes").astype(int).to_numpy()
y_test = (test["y"] == "yes").astype(int).to_numpy()

split_summary = pd.DataFrame({
    "rows": [len(train), len(val), len(test)],
    "positive": [y_train.sum(), y_val.sum(), y_test.sum()],
    "positive_rate": [y_train.mean(), y_val.mean(), y_test.mean()],
}, index=["Train", "Validation", "Test"])

split_summary

# Visualise class prevalence across the chronological split

plot_data = split_summary.copy()

x_labels = [
    f"Train\n(n={plot_data.loc['Train', 'rows']:,})",
    f"Validation\n(n={plot_data.loc['Validation', 'rows']:,})",
    f"Test\n(n={plot_data.loc['Test', 'rows']:,})"
]

rates = plot_data["positive_rate"].values * 100

plt.figure(figsize=(8, 4.8))

bars = plt.bar(x_labels, rates)

for bar, rate in zip(bars, rates):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height() + 0.7,
        f"{rate:.2f}%",
        ha="center",
        va="bottom",
        fontweight="bold"
    )

plt.ylabel("Positive class rate (%)")
plt.title(
    "Subscription prevalence rises across the chronological split",
    fontweight="bold"
)

plt.ylim(0, max(rates) + 5)
plt.grid(axis="y", alpha=0.25)
plt.tight_layout()
plt.show()

"""The split is intentionally not shuffled. The large change in positive rate across the three partitions is part of the deployment challenge rather than something to remove by stratification.

## Preprocessing
"""

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_columns),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_columns),
    ]
)

X_train = preprocessor.fit_transform(train[model_features])
X_val = preprocessor.transform(val[model_features])
X_test = preprocessor.transform(test[model_features])

feature_names = preprocessor.get_feature_names_out()

print("Train matrix:", X_train.shape)
print("Validation matrix:", X_val.shape)
print("Test matrix:", X_test.shape)
print("Encoded input dimension:", len(feature_names))

"""Standard SMOTE is used on the **encoded feature space**. Because one-hot-derived columns can become fractional after interpolation, the synthetic rows are treated as training vectors, not as literal reconstructed customer records. Validation and test rows remain untouched.

## Evaluation helpers
"""

def best_f1_threshold(y_true, scores):
    precision, recall, thresholds = precision_recall_curve(y_true, scores)
    f1 = 2 * precision * recall / (precision + recall + 1e-12)

    # precision_recall_curve returns one extra precision/recall point.
    best_index = np.argmax(f1[:-1])
    return float(thresholds[best_index]), float(f1[best_index])


def evaluate_scores(y_true, scores, threshold, top_fraction=0.10):
    predictions = (scores >= threshold).astype(int)

    k = max(1, int(len(y_true) * top_fraction))
    top_index = np.argsort(scores)[::-1][:k]
    precision_at_k = y_true[top_index].mean()
    base_rate = y_true.mean()

    tn, fp, fn, tp = confusion_matrix(y_true, predictions).ravel()

    return {
        "accuracy": accuracy_score(y_true, predictions),
        "precision": precision_score(y_true, predictions, zero_division=0),
        "recall": recall_score(y_true, predictions, zero_division=0),
        "f1": f1_score(y_true, predictions, zero_division=0),
        "roc_auc": roc_auc_score(y_true, scores),
        "ap": average_precision_score(y_true, scores),
        "precision_at_10": precision_at_k,
        "lift_at_10": precision_at_k / base_rate,
        "threshold": threshold,
        "tn": int(tn),
        "fp": int(fp),
        "fn": int(fn),
        "tp": int(tp),
    }


def result_row(name, y_true, scores, threshold):
    row = evaluate_scores(y_true, scores, threshold)
    row["model"] = name
    return row

"""## Sanity baseline: always predict no"""

majority_test_accuracy = (y_test == 0).mean()
full_data_majority_accuracy = (y == 0).mean()

print(f"Always-no accuracy on the full dataset: {full_data_majority_accuracy:.3f}")
print(f"Always-no accuracy on the chronological test set: {majority_test_accuracy:.3f}")

"""## Ablation 1: duration"""

# Main baseline: no duration, no SMOTE.
lr_baseline = LogisticRegression(C=1.0, max_iter=1000, solver="liblinear", random_state=SEED)
lr_baseline.fit(X_train, y_train)

lr_base_val_scores = lr_baseline.predict_proba(X_val)[:, 1]
lr_base_test_scores = lr_baseline.predict_proba(X_test)[:, 1]

# Same model family, but duration is added back only for this ablation.
numeric_with_duration = numeric_columns + ["duration"]
features_with_duration = numeric_with_duration + categorical_columns

preprocessor_with_duration = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_with_duration),
        ("cat", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_columns),
    ]
)

X_train_duration = preprocessor_with_duration.fit_transform(train[features_with_duration])
X_val_duration = preprocessor_with_duration.transform(val[features_with_duration])
X_test_duration = preprocessor_with_duration.transform(test[features_with_duration])

lr_with_duration = LogisticRegression(C=1.0, max_iter=1000, solver="liblinear", random_state=SEED)
lr_with_duration.fit(X_train_duration, y_train)

lr_duration_val_scores = lr_with_duration.predict_proba(X_val_duration)[:, 1]
lr_duration_test_scores = lr_with_duration.predict_proba(X_test_duration)[:, 1]

duration_ablation = pd.DataFrame([
    {
        "setting": "without duration",
        "validation_ap": average_precision_score(y_val, lr_base_val_scores),
        "test_ap": average_precision_score(y_test, lr_base_test_scores),
        "test_roc_auc": roc_auc_score(y_test, lr_base_test_scores),
    },
    {
        "setting": "with duration",
        "validation_ap": average_precision_score(y_val, lr_duration_val_scores),
        "test_ap": average_precision_score(y_test, lr_duration_test_scores),
        "test_roc_auc": roc_auc_score(y_test, lr_duration_test_scores),
    },
])

duration_ablation.round(4)

"""## SMOTE ratio experiment"""

smote_rows = []

# Keep the exact LR setup fixed so the only change here is oversampling.
smote_rows.append({
    "setting": "No SMOTE",
    "ratio": np.nan,
    "train_rows": len(X_train),
    "positive_rate_after": y_train.mean(),
    "validation_ap": average_precision_score(y_val, lr_base_val_scores),
    "validation_roc_auc": roc_auc_score(y_val, lr_base_val_scores),
})

current_ratio = y_train.sum() / (len(y_train) - y_train.sum())
ratio_candidates = [0.10, 0.25, 0.50, 1.00]
ratio_candidates = [r for r in ratio_candidates if r > current_ratio]

for ratio in ratio_candidates:
    smote = SMOTE(sampling_strategy=ratio, random_state=SEED, k_neighbors=5)
    X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

    model = LogisticRegression(C=1.0, max_iter=1000, solver="liblinear", random_state=SEED)
    model.fit(X_resampled, y_resampled)
    val_scores = model.predict_proba(X_val)[:, 1]

    smote_rows.append({
        "setting": f"SMOTE {ratio:.2f}",
        "ratio": ratio,
        "train_rows": len(X_resampled),
        "positive_rate_after": y_resampled.mean(),
        "validation_ap": average_precision_score(y_val, val_scores),
        "validation_roc_auc": roc_auc_score(y_val, val_scores),
    })

smote_experiment = pd.DataFrame(smote_rows)
smote_experiment.round(4)

smote_only = smote_experiment.dropna(subset=["ratio"])
best_smote_row = smote_only.loc[smote_only["validation_ap"].idxmax()]
selected_smote_ratio = float(best_smote_row["ratio"])

print(f"Selected SMOTE ratio: {selected_smote_ratio:.2f}")
print(f"Validation AP: {best_smote_row['validation_ap']:.4f}")

# Visualise the SMOTE ratio experiment

plot_df = smote_experiment.copy()

x_labels = [
    "None" if pd.isna(ratio) else f"{ratio:.2f}"
    for ratio in plot_df["ratio"]
]

ap_values = plot_df["validation_ap"].values
x = np.arange(len(plot_df))

fig, ax = plt.subplots(figsize=(8, 4.8))

# Main line
ax.plot(
    x,
    ap_values,
    marker="o",
    linewidth=2,
    markersize=6
)

# Selected ratio
selected_idx = plot_df.index[
    plot_df["ratio"].eq(selected_smote_ratio)
][0]

ax.scatter(
    selected_idx,
    ap_values[selected_idx],
    s=120,
    zorder=4
)

# Value labels
for i, value in enumerate(ap_values):
    if i == selected_idx:
        y_offset = 10
    elif i in [0, 1]:
        y_offset = 9
    else:
        y_offset = -14

    ax.annotate(
        f"{value:.4f}",
        (i, value),
        xytext=(0, y_offset),
        textcoords="offset points",
        ha="center",
        fontsize=9
    )

# Selected annotation
ax.annotate(
    "Selected: 0.25",
    xy=(selected_idx, ap_values[selected_idx]),
    xytext=(selected_idx + 0.65, ap_values[selected_idx] + 0.0012),
    arrowprops=dict(
        arrowstyle="->",
        linewidth=1.1
    ),
    fontsize=9.5,
    fontweight="bold"
)

ax.set_xticks(x)
ax.set_xticklabels(x_labels)

ax.set_xlabel("SMOTE sampling strategy (minority / majority)")
ax.set_ylabel("Validation average precision")

ax.set_title(
    "Validation performance across SMOTE ratios",
    fontsize=13,
    fontweight="bold",
    pad=12
)

# More breathing room
ax.set_ylim(
    ap_values.min() - 0.0015,
    ap_values.max() + 0.0030
)

ax.grid(
    axis="y",
    alpha=0.25,
    linewidth=0.8
)

ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.tight_layout()
plt.show()

final_smote = SMOTE(
    sampling_strategy=selected_smote_ratio,
    random_state=SEED,
    k_neighbors=5,
)

X_train_smote, y_train_smote = final_smote.fit_resample(X_train, y_train)

before_after_smote = pd.DataFrame({
    "rows": [len(X_train), len(X_train_smote)],
    "positive": [y_train.sum(), y_train_smote.sum()],
    "negative": [(y_train == 0).sum(), (y_train_smote == 0).sum()],
    "positive_rate": [y_train.mean(), y_train_smote.mean()],
}, index=["Before SMOTE", "After SMOTE"])

before_after_smote

"""## Ablation 2: Logistic Regression before and after SMOTE"""

lr_smote = LogisticRegression(C=1.0, max_iter=1000, solver="liblinear", random_state=SEED)
lr_smote.fit(X_train_smote, y_train_smote)

lr_smote_val_scores = lr_smote.predict_proba(X_val)[:, 1]
lr_smote_test_scores = lr_smote.predict_proba(X_test)[:, 1]

# Fixed 0.5 threshold: this is the cleanest classification ablation.
smote_ablation_fixed = pd.DataFrame([
    result_row("LR baseline", y_test, lr_base_test_scores, 0.5),
    result_row("LR + SMOTE", y_test, lr_smote_test_scores, 0.5),
]).set_index("model")

smote_ablation_fixed[[
    "accuracy", "precision", "recall", "f1", "roc_auc", "ap"
]].round(4)

# In the main deployment comparison, each threshold is selected on validation data.
lr_base_threshold, lr_base_val_f1 = best_f1_threshold(y_val, lr_base_val_scores)
lr_smote_threshold, lr_smote_val_f1 = best_f1_threshold(y_val, lr_smote_val_scores)

smote_ablation_tuned = pd.DataFrame([
    result_row("LR baseline", y_test, lr_base_test_scores, lr_base_threshold),
    result_row("LR + SMOTE", y_test, lr_smote_test_scores, lr_smote_threshold),
]).set_index("model")

smote_ablation_tuned[[
    "threshold", "accuracy", "precision", "recall", "f1", "roc_auc", "ap"
]].round(4)

"""## Random Forest"""

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=12,
    min_samples_leaf=5,
    criterion="gini",
    random_state=SEED,
    n_jobs=-1,
)

rf.fit(X_train_smote, y_train_smote)

rf_val_scores = rf.predict_proba(X_val)[:, 1]
rf_test_scores = rf.predict_proba(X_test)[:, 1]

print("Validation AP:", round(average_precision_score(y_val, rf_val_scores), 4))

"""## Linear SVM"""

svm = LinearSVC(
    C=1.0,
    dual=False,
    max_iter=5000,
    random_state=SEED,
)
svm.fit(X_train_smote, y_train_smote)

svm_val_scores = svm.decision_function(X_val)
svm_test_scores = svm.decision_function(X_test)

print("Validation AP:", round(average_precision_score(y_val, svm_val_scores), 4))

"""## Neural network"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)


class BankMLP(nn.Module):
    def __init__(self, input_dim):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 1),
        )

    def forward(self, x):
        return self.layers(x).squeeze(1)


X_train_tensor = torch.tensor(X_train_smote, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train_smote, dtype=torch.float32)
X_val_tensor = torch.tensor(X_val, dtype=torch.float32)
y_val_tensor = torch.tensor(y_val, dtype=torch.float32)

train_loader = DataLoader(
    TensorDataset(X_train_tensor, y_train_tensor),
    batch_size=256,
    shuffle=True,
)

val_loader = DataLoader(
    TensorDataset(X_val_tensor, y_val_tensor),
    batch_size=1024,
    shuffle=False,
)

nn_model = BankMLP(X_train_smote.shape[1]).to(device)
criterion = nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(nn_model.parameters(), lr=0.001)

max_epochs = 50
patience = 5
best_val_loss = float("inf")
best_state = None
wait = 0

history = {"train_loss": [], "val_loss": []}

for epoch in range(1, max_epochs + 1):
    nn_model.train()
    train_loss_sum = 0.0

    for X_batch, y_batch in train_loader:
        X_batch = X_batch.to(device)
        y_batch = y_batch.to(device)

        optimizer.zero_grad()
        logits = nn_model(X_batch)
        loss = criterion(logits, y_batch)
        loss.backward()
        optimizer.step()

        train_loss_sum += loss.item() * len(X_batch)

    train_loss = train_loss_sum / len(train_loader.dataset)

    nn_model.eval()
    val_loss_sum = 0.0

    with torch.no_grad():
        for X_batch, y_batch in val_loader:
            X_batch = X_batch.to(device)
            y_batch = y_batch.to(device)
            logits = nn_model(X_batch)
            loss = criterion(logits, y_batch)
            val_loss_sum += loss.item() * len(X_batch)

    val_loss = val_loss_sum / len(val_loader.dataset)
    history["train_loss"].append(train_loss)
    history["val_loss"].append(val_loss)

    print(f"Epoch {epoch:02d} | train {train_loss:.4f} | val {val_loss:.4f}")

    if val_loss < best_val_loss - 1e-4:
        best_val_loss = val_loss
        best_state = copy.deepcopy(nn_model.state_dict())
        wait = 0
    else:
        wait += 1
        if wait >= patience:
            print("Early stopping")
            break

nn_model.load_state_dict(best_state)
print("Best validation BCE:", round(best_val_loss, 4))

plt.figure(figsize=(7, 4))
plt.plot(range(1, len(history["train_loss"]) + 1), history["train_loss"], label="Train")
plt.plot(range(1, len(history["val_loss"]) + 1), history["val_loss"], label="Validation")
plt.xlabel("Epoch")
plt.ylabel("BCE loss")
plt.title("Neural network training")
plt.legend()
plt.tight_layout()
plt.savefig(FIG_DIR / "nn_loss_curve.png", dpi=160)
plt.show()

def nn_predict_scores(model, X):
    model.eval()
    X_tensor = torch.tensor(X, dtype=torch.float32, device=device)
    with torch.no_grad():
        logits = model(X_tensor)
        return torch.sigmoid(logits).cpu().numpy()


nn_val_scores = nn_predict_scores(nn_model, X_val)
nn_test_scores = nn_predict_scores(nn_model, X_test)

print("Validation AP:", round(average_precision_score(y_val, nn_val_scores), 4))

"""## Validation thresholds"""

validation_scores = {
    "LR baseline": lr_base_val_scores,
    "LR + SMOTE": lr_smote_val_scores,
    "Random Forest": rf_val_scores,
    "Linear SVM": svm_val_scores,
    "Neural Network": nn_val_scores,
}

thresholds = {}
threshold_rows = []

for name, scores in validation_scores.items():
    threshold, val_f1 = best_f1_threshold(y_val, scores)
    thresholds[name] = threshold
    threshold_rows.append({"model": name, "threshold": threshold, "validation_f1": val_f1})

threshold_table = pd.DataFrame(threshold_rows).set_index("model")
threshold_table.round(4)

"""## Final chronological test results"""

test_scores = {
    "LR baseline": lr_base_test_scores,
    "LR + SMOTE": lr_smote_test_scores,
    "Random Forest": rf_test_scores,
    "Linear SVM": svm_test_scores,
    "Neural Network": nn_test_scores,
}

result_rows = []
for name, scores in test_scores.items():
    result_rows.append(result_row(name, y_test, scores, thresholds[name]))

results = pd.DataFrame(result_rows).set_index("model")

result_columns = [
    "accuracy", "precision", "recall", "f1", "roc_auc", "ap",
    "precision_at_10", "lift_at_10", "threshold", "tn", "fp", "fn", "tp"
]
results = results[result_columns]
results.round(4)

# Precision-recall operating points at validation-selected thresholds

fig, ax = plt.subplots(figsize=(8, 5.5))

points = {
    "LR": (
        results.loc["LR baseline", "precision"],
        results.loc["LR baseline", "recall"]
    ),
    "LR + SMOTE": (
        results.loc["LR + SMOTE", "precision"],
        results.loc["LR + SMOTE", "recall"]
    ),
    "RF": (
        results.loc["Random Forest", "precision"],
        results.loc["Random Forest", "recall"]
    ),
    "SVM": (
        results.loc["Linear SVM", "precision"],
        results.loc["Linear SVM", "recall"]
    ),
    "NN": (
        results.loc["Neural Network", "precision"],
        results.loc["Neural Network", "recall"]
    )
}

# Plot points
for label, (precision_value, recall_value) in points.items():
    ax.scatter(
        precision_value,
        recall_value,
        s=95,
        zorder=3
    )

# RF
ax.annotate(
    f"RF\nP={points['RF'][0]:.3f}, R={points['RF'][1]:.3f}",
    xy=points["RF"],
    xytext=(10, 8),
    textcoords="offset points",
    fontsize=9,
    va="bottom"
)

# NN
ax.annotate(
    f"NN\nP={points['NN'][0]:.3f}, R={points['NN'][1]:.3f}",
    xy=points["NN"],
    xytext=(10, 6),
    textcoords="offset points",
    fontsize=9,
    va="bottom"
)

cluster_labels = {
    "LR + SMOTE": (0.515, 0.348),
    "SVM":        (0.515, 0.317),
    "LR":         (0.515, 0.282)
}

for label, text_pos in cluster_labels.items():

    p, r = points[label]

    ax.annotate(
        f"{label}  (P={p:.3f}, R={r:.3f})",
        xy=(p, r),
        xytext=text_pos,
        textcoords="data",
        fontsize=9,
        va="center",
        arrowprops=dict(
    arrowstyle="-",
    linewidth=0.9,
    alpha=0.7
)
    )

# Axis labels
ax.set_xlabel("Precision", fontsize=11)
ax.set_ylabel("Recall", fontsize=11)

# Cleaner title
ax.set_title(
    "Precision–recall trade-off at validation-selected thresholds",
    fontsize=13,
    fontweight="bold",
    pad=16
)

# Axis limits chosen to keep all models visible
ax.set_xlim(0.405, 0.575)
ax.set_ylim(0.26, 0.68)

# Light grid
ax.grid(
    alpha=0.22,
    linewidth=0.8
)

# Cleaner borders
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)

plt.tight_layout()
plt.show()

results.to_csv(OUT_DIR / "final_test_results.csv")
smote_experiment.to_csv(OUT_DIR / "smote_ratio_experiment.csv", index=False)
duration_ablation.to_csv(OUT_DIR / "duration_ablation.csv", index=False)
threshold_table.to_csv(OUT_DIR / "validation_thresholds.csv")

"""## Precision-recall curves"""

plt.figure(figsize=(7, 5))

for name, scores in test_scores.items():
    precision, recall, _ = precision_recall_curve(y_test, scores)
    plt.plot(recall, precision, label=f"{name} (AP={average_precision_score(y_test, scores):.3f})")

plt.axhline(y_test.mean(), linestyle="--", label="Test positive rate")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-recall curves on chronological test set")
plt.legend(fontsize=8)
plt.tight_layout()
plt.savefig(FIG_DIR / "precision_recall_curves.png", dpi=160)
plt.show()

"""## ROC curves"""

plt.figure(figsize=(7, 5))

for name, scores in test_scores.items():
    fpr, tpr, _ = roc_curve(y_test, scores)
    plt.plot(fpr, tpr, label=f"{name} (AUC={roc_auc_score(y_test, scores):.3f})")

plt.plot([0, 1], [0, 1], linestyle="--")
plt.xlabel("False positive rate")
plt.ylabel("True positive rate")
plt.title("ROC curves on chronological test set")
plt.legend(fontsize=8)
plt.tight_layout()
plt.savefig(FIG_DIR / "roc_curves.png", dpi=160)
plt.show()

"""## Selected metric plots"""

for metric, label in [
    ("ap", "Average Precision"),
    ("f1", "F1"),
    ("precision_at_10", "Precision@10%"),
]:
    plt.figure(figsize=(8, 4))
    plt.bar(results.index, results[metric])
    plt.ylabel(label)
    plt.xticks(rotation=25, ha="right")
    plt.title(f"{label} on chronological test set")
    plt.tight_layout()
    plt.savefig(FIG_DIR / f"{metric}.png", dpi=160)
    plt.show()

"""## Confusion matrices"""

# Three representative models are enough for the report body.
for name in ["LR baseline", "Random Forest", "Neural Network"]:
    predictions = (test_scores[name] >= thresholds[name]).astype(int)
    matrix = confusion_matrix(y_test, predictions)

    display = ConfusionMatrixDisplay(matrix, display_labels=["No", "Yes"])
    display.plot()
    plt.title(name)
    plt.tight_layout()
    safe_name = name.lower().replace(" ", "_")
    plt.savefig(FIG_DIR / f"confusion_{safe_name}.png", dpi=160)
    plt.show()

"""## Top-10% targeted marketing view"""

top_rows = []
k = max(1, int(len(y_test) * 0.10))

for name, scores in test_scores.items():
    top_index = np.argsort(scores)[::-1][:k]
    subscribers = int(y_test[top_index].sum())
    precision_at_10 = subscribers / k

    top_rows.append({
        "model": name,
        "customers_selected": k,
        "true_subscribers": subscribers,
        "precision_at_10": precision_at_10,
        "lift_at_10": precision_at_10 / y_test.mean(),
    })

top10_table = pd.DataFrame(top_rows).set_index("model")
top10_table.round(4)

"""## Error analysis by month"""

# Use the NN as one representative model for temporal error analysis.
analysis_model = "Neural Network"
analysis_scores = test_scores[analysis_model]
analysis_predictions = (analysis_scores >= thresholds[analysis_model]).astype(int)

month_analysis = test[["month"]].copy()
month_analysis["actual"] = y_test
month_analysis["predicted"] = analysis_predictions
month_analysis["score"] = analysis_scores

month_summary = month_analysis.groupby("month").agg(
    rows=("actual", "size"),
    actual_positive_rate=("actual", "mean"),
    predicted_positive_rate=("predicted", "mean"),
    mean_score=("score", "mean"),
)

month_order = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"]
month_summary = month_summary.reindex([m for m in month_order if m in month_summary.index])
month_summary.round(4)

plt.figure(figsize=(9, 4))
plt.plot(month_summary.index, month_summary["actual_positive_rate"], marker="o", label="Actual")
plt.plot(month_summary.index, month_summary["predicted_positive_rate"], marker="o", label="Predicted positive")
plt.ylabel("Rate")
plt.title(f"Monthly error pattern: {analysis_model}")
plt.legend()
plt.tight_layout()
plt.savefig(FIG_DIR / "monthly_error_pattern.png", dpi=160)
plt.show()

"""## Save trained objects"""

joblib.dump(preprocessor, OUT_DIR / "preprocessor.joblib")
joblib.dump(lr_baseline, OUT_DIR / "lr_baseline.joblib")
joblib.dump(lr_smote, OUT_DIR / "lr_smote.joblib")
joblib.dump(rf, OUT_DIR / "random_forest.joblib")
joblib.dump(svm, OUT_DIR / "linear_svm.joblib")

torch.save(
    {
        "state_dict": nn_model.state_dict(),
        "input_dim": X_train_smote.shape[1],
        "hidden_layers": [64, 32],
    },
    OUT_DIR / "neural_network.pt",
)

with open(OUT_DIR / "thresholds.json", "w") as f:
    json.dump({name: float(value) for name, value in thresholds.items()}, f, indent=2)

print("Saved models and result files to:", OUT_DIR.resolve())

"""## Simple deployment example"""

# This function deliberately uses only deployable features; duration is not accepted.
def score_customer_with_lr(customer):
    row = pd.DataFrame([customer])
    transformed = preprocessor.transform(row[model_features])
    return float(lr_smote.predict_proba(transformed)[:, 1][0])


example_customer = test.iloc[0][model_features].to_dict()
example_score = score_customer_with_lr(example_customer)

print("Subscription propensity score:", round(example_score, 4))
print("Validation-selected threshold:", round(thresholds["LR + SMOTE"], 4))
print("Predicted class:", int(example_score >= thresholds["LR + SMOTE"]))